"""empty message

Revision ID: 04333c8055a5
Revises: a41c7220a9df
Create Date: 2022-11-23 12:36:21.305576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04333c8055a5'
down_revision = 'a41c7220a9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', sa.String(length=50), nullable=False))
    op.add_column('planets', sa.Column('population', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###
