"""empty message

Revision ID: a41c7220a9df
Revises: e34e49df2354
Create Date: 2022-11-23 12:14:07.406297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41c7220a9df'
down_revision = 'e34e49df2354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('height', sa.String(length=15), nullable=False))
    op.add_column('people', sa.Column('gender', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'gender')
    op.drop_column('people', 'height')
    # ### end Alembic commands ###
