"""empty message

Revision ID: e34e49df2354
Revises: 9ee3599a1246
Create Date: 2022-11-23 11:56:16.016575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e34e49df2354'
down_revision = '9ee3599a1246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'height')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('height', mysql.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
